# Generated by Django 6.0.7 on 2026-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category_alter_task_status_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attchment',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
