# Generated by Django 6.0.7 on 2026-07-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_attchment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='attchment',
            new_name='attachment',
        ),
    ]
